#!/bin/bash

INTERFAZ_RED_INTERNA=$2
INTERFAZ_OTRO_ROUTER=$3

sysctl -w net.ipv4.ip_forward=1

if [ $1 == "A" ]
then

	# AGREGAMOS LA IP DE LA RED INTERNA A LA INTERFAZ Y LEVANTAMOS
	ip addr add 10.22.0.1/29 dev $INTERFAZ_RED_INTERNA
	ip link set $INTERFAZ_RED_INTERNA up

	# AGREGAMOS LA IP PÚBLICA CON LA SE COMUNICARÁ A CON B Y LEVANTAMOS
	ip addr add 10.32.0.1/30 dev $INTERFAZ_OTRO_ROUTER
	ip link set $INTERFAZ_OTRO_ROUTER up

	# DIRIGIMOS TODO EL TRÁFICO DEL ROUTER AL SIGUIENTE ROUTER (B)
	ip route add default via 10.32.0.2 dev $INTERFAZ_OTRO_ROUTER

	# pendiente ver si necesita msaquerade
	

elif [ $1 == "D" ]
then

	# AGREGAMOS LA IP DE LA RED INTERNA A LA INTERFAZ Y LEVANTAMOS
	ip addr add 10.25.0.1/29 dev $INTERFAZ_RED_INTERNA
	ip link set $INTERFAZ_RED_INTERNA up

	# AGREGAMOS LA IP PÚBLICA CON LA SE COMUNICARÁ D CON C Y LEVANTAMOS
	ip addr add 10.35.0.2/30 dev $INTERFAZ_OTRO_ROUTER
	ip link set $INTERFAZ_OTRO_ROUTER up

	# DIRIGIMOS TODO EL TRÁFICO DEL ROUTER AL SIGUIENTE ROUTER (C)
	ip route add default via 10.35.0.1 dev $INTERFAZ_OTRO_ROUTER

	# pendiente ver si necesita msaquerade

fi

# CONFIGURAMOS LA TABLA NAT PARA ENMASCARAR EL PAQUETE LUEGO DE ENRUTARLO
# AL ROUTER PERO ANTES DE ENVIARLO
# iptables -t nat -A POSTROUTING -o $INTERFAZ_OTRO_ROUTER -j MASQUERADE
